### ISSUE TITLE
Cannot generate access_token for data fabric API as per documentation

### ISSUE THREAD

**Issue by mscelnik** [veracity/Python-SDK-for-Veracity#3]
The Veracity documentation (https://developer.veracity.com/docs/section/identity/authentication/web-native#authenticating-a-user) suggests you can provide the data fabric API scope to the authentication flow and get an access token.  This process works for the services API scope but not for the data fabric API scope.

I don't think the issue is with the Python SDK.  Perhaps the Veracity documentation is inaccurate or incomplete?

See [interactive_auth.py](https://github.com/mscelnik/Python-SDK-for-Veracity/blob/develop/examples/interactive_auth.py) for example usage.

**Comment by mingderekwang** [comment]
Hi Matt, you can use same scope for both data api and My service api.
